# Generated by Django 3.1.5 on 2021-01-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='role',
            field=models.CharField(choices=[('MENTOR', 'Mentor'), ('STUDENT', 'Student')], default='STUDENT', max_length=16),
        ),
    ]
